import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: "1",
    name: "Men Slim Fit Solid Spread Collar Casual Shirt",
    brand: "Highlander",
    idealFor: ["MEN"],
    originalPrice: 1249,
    discount: 56,
    discountedPrice: 549,
    rating: 4,
    sizes: ["S", "M", "L", "XL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20210316/IIPo/604fb2c1f997dd5c40115f5b/the_indian_garage_co_beige_checked_slim_fit_shirt_with_patch_pocket.jpg",
  },
  {
    id: "8",
    name: "Floral print Regular Fusion wear Dress women maxi dress",
    brand: "Aavasa",
    idealFor: ["WOMEN"],
    originalPrice: 1399,
    discount: 68,
    discountedPrice: 439,
    rating: 3.3,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20221003/tMXy/633ac9b9aeb269659c210774/shewill_red_floral_printed_regular_fusion_wear_sets_.jpg",
  },
  {
    id: "2",
    name: "Men Slim Fit Printed Casual Shirt cotton casual wear",
    brand: "Highlander",
    idealFor: ["MEN"],
    originalPrice: 1049,
    discount: 52,
    discountedPrice: 527,
    rating: 4.1,
    sizes: ["S", "M", "L", "XL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20220629/Glgr/62bb49aaaeb26921af4da953/british_club_white_slim_fit_shirt_with_patch_pocket.jpg",
  },
  {
    id: "7",
    name: "Women Embellished Georgette skirt-suit-set",
    brand: "Aavasa",
    idealFor: ["WOMEN"],
    originalPrice: 1999,
    discount: 75,
    discountedPrice: 494,
    rating: 3.9,
    sizes: ["S", "M", "L", "XXL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20220623/muco/62b45282aeb26921af42d344/kvs_fab_yellow_embellished_georgette_skirt-_suit-set.jpg",
  },
  {
    id: "3",
    name: "Men Regular Fit Checkered Spread Collar Casual Shirt",
    brand: "Polo",
    idealFor: ["MEN"],
    originalPrice: 999,
    discount: 40,
    discountedPrice: 599,
    rating: 4.1,
    sizes: ["M"],
    img: "https://assets.ajio.com/medias/sys_master/root/20211023/6Qlf/617313e1aeb2690110a3e315/the_indian_garage_co_white_slim_fit_striped_shirt_with_patch_pocket.jpg",
  },
  {
    id: "4",
    name: "Men Slim Fit Self Design Slim Collar Casual Shirt",
    brand: "Allen Solly",
    idealFor: ["MEN"],
    originalPrice: 1499,
    discount: 40,
    discountedPrice: 899,
    rating: 3.9,
    sizes: ["M"],
    img: "https://assets.ajio.com/medias/sys_master/root/20201221/WkAq/5fe04e55f997dd8c83da022b/the_indian_garage_co_navy_blue_gradation_striped_slim_fit_shirt.jpg",
  },
  {
    id: "5",
    name: "Unisex Jacket Viscose Rayon stylish red blue trending jacket",
    brand: "Polo",
    idealFor: ["UNISEX"],
    originalPrice: 1999,
    discount: 75,
    discountedPrice: 499,
    rating: 4.2,
    sizes: ["S", "M", "L", "XL", "XXL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20210730/4MzO/61042190f997ddb312412171/yb_dnmx_navy_blue_%26_red_colourblock_zip-front_hooded_jacket.jpg",
  },
  {
    id: "6",
    name: "Women Kurta and Palazzo Set Pure Cotton",
    brand: "Libas",
    idealFor: ["WOMEN"],
    originalPrice: 1119,
    discount: 60,
    discountedPrice: 799,
    rating: 4.3,
    sizes: ["XS", "S", "M", "L", "XXL"],
    img: "https://assets.ajio.com/medias/sys_master/root/20220322/zZrx/6239e35bf997dd03e22576a3/gulmohar_jaipur_navy_blue_floral_print_flared_kurta.jpg",
  },
];
